import asyncio
import sys
from pathlib import Path
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client


async def run_client():
    # Locate the MCP server script
    server_script = Path(__file__).parent / "markdown_to_pdf_mcp.py"

    if not server_script.exists():
        print(
            f"Error: Server script not found at {server_script}", file=sys.stderr)
        sys.exit(1)

    # Configure the server connection using stdio transport
    server_params = StdioServerParameters(
        command=sys.executable,
        args=[str(server_script), "--run-mcp"],
        env=None
    )

    print(f"Connecting to MCP server: {server_script}...")

    async with stdio_client(server_params) as (read_stream, write_stream):
        async with ClientSession(read_stream, write_stream) as session:
            # Initialize the session
            print("Initializing session...")
            await session.initialize()

            # List available tools to confirm communication is established
            print("\nListing available tools:")
            tools_response = await session.list_tools()
            for tool in tools_response.tools:
                print(f"  - {tool.name}: {tool.description}")

            # Define markdown content to convert
            markdown_content = """# Hello from MCP Client
            This PDF was generated by connecting to the MCP Server over stdio.

            ## Features
            - Automatic Header Formatting
            - Automatic Text Wrapping
            - Easy integration via Python's `mcp` library

            Enjoy PDF generation!
            """
            output_path = str(Path(__file__).parent / "client_output.pdf")

            print(f"\nInvoking 'convert_markdown_to_pdf'...")
            print(f"Output path: {output_path}")

            # Execute the tool
            result = await session.call_tool(
                "convert_markdown_to_pdf",
                arguments={
                    "markdown_content": markdown_content,
                    "output_path": output_path
                }
            )

            # Print the tool response
            print("\nServer Output:")
            if result and hasattr(result, 'content'):
                for content_block in result.content:
                    if hasattr(content_block, 'text'):
                        print(content_block.text)
                    else:
                        print(content_block)
            else:
                print(result)


if __name__ == "__main__":
    asyncio.run(run_client())
